// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"@@/global-layout","id":"1"},"2":{"name":"登录","path":"/login","layout":false,"id":"2"},"3":{"name":"注册","path":"/register","layout":false,"id":"3"},"4":{"name":"会话","path":"/home","menu":{"category":"function","sort":1},"parentId":"@@/global-layout","id":"4"},"5":{"name":"对话","path":"/chat/:id","menu":{"category":"function","hidden":true},"parentId":"@@/global-layout","id":"5"},"6":{"name":"新建对话","path":"/new/:id","menu":{"category":"function","hidden":true},"parentId":"@@/global-layout","id":"6"},"7":{"name":"知识库","path":"/knowledge","menu":{"category":"function","sort":4},"parentId":"@@/global-layout","id":"7"},"8":{"name":"搜索","path":"/search","menu":{"category":"system","sort":1},"parentId":"@@/global-layout","id":"8"},"9":{"name":"管理","path":"/management","menu":{"category":"system","sort":2},"parentId":"@@/global-layout","id":"9"},"10":{"name":"系统设置","path":"/management/system","parentId":"9","id":"10"},"11":{"name":"模型管理","path":"/management/models","parentId":"9","id":"11"},"12":{"name":"屏蔽词管理","path":"/management/sensitive","parentId":"9","id":"12"},"13":{"name":"团队管理","path":"/team","menu":{"category":"system","sort":1},"parentId":"@@/global-layout","id":"13"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Login__register" */'@/pages/Login/register.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Chat__$id" */'@/pages/Chat/$id.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__New__$id" */'@/pages/New/$id.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Knowledge__index" */'@/pages/Knowledge/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Search__index" */'@/pages/Search/index.tsx')),
'9': React.lazy(() => import('./EmptyRoute')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Management__System" */'@/pages/Management/System.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Management__Models" */'@/pages/Management/Models.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Management__Sensitive" */'@/pages/Management/Sensitive.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Team__index" */'@/pages/Team/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/gift/big-model/AI-YS-FE/src/layouts/index.tsx')),
},
  };
}
