// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/gift/big-model/AI-YS-FE/src/models/global';
import model_2 from '/Users/gift/big-model/AI-YS-FE/src/models/user';
import model_3 from '/Users/gift/big-model/AI-YS-FE/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: 'user', model: model_2 },
model_3: { namespace: '@@initialState', model: model_3 },
} as const
