// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import LogoPNG from '@/assets/images/logo.png';
import React from 'react';

const LogoIcon: React.FC = () => {
  return <img src={LogoPNG} alt="logo" />;
};

export default LogoIcon;
